<a href="https://colab.research.google.com/github/Charanvitha/2303A51408-Batch-07/blob/main/Lab_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2303A51408
Batch-07

**Matrix Addition and Subtraction**

In [ ]:
import numpy as np

In [ ]:
#Creation of 2D arrays
arr2D_1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2D_2=np.array([[15,11,20],[19,24,15],[26,17,29]])

In [ ]:
#Element wise Addition
add_arr=np.add(arr2D_1,arr2D_2)

#Element wise Subtraction
sub_arr=np.subtract(arr2D_2,arr2D_1)



In [ ]:
#Display original matrices and results
print("Original Matrix 1:")
print(arr2D_1)
print("Original Matrix 2:")
print(arr2D_2)

#results after addition and subtraction
print("Addition Result:")
print(add_arr)
print("Subtraction Result:")
print(sub_arr)

Original Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Original Matrix 2:
[[15 11 20]
 [19 24 15]
 [26 17 29]]
Addition Result:
[[16 13 23]
 [23 29 21]
 [33 25 38]]
Subtraction Result:
[[14  9 17]
 [15 19  9]
 [19  9 20]]


**2D Matrix Multiplication (Dot Product)**

In [ ]:
#Create two compatible 2D arrays (e.g., 3x2 and 2x3)
arr2D_3=np.array([[1,2],[4,5],[7,8]])
arr2D_4=np.array([[15,11,20],[19,24,15]])

In [ ]:
#Use np.dot() or @ operator to perform dot product
result_dot=np.dot(arr2D_3,arr2D_4)

In [ ]:
#Print intermediate and final results
print("Matrix 1:")
print(arr2D_3)
print("Matrix 2:")
print(arr2D_4)
print("Dot Product Result:")
print(result_dot)

Matrix 1:
[[1 2]
 [4 5]
 [7 8]]
Matrix 2:
[[15 11 20]
 [19 24 15]]
Dot Product Result:
[[ 53  59  50]
 [155 164 155]
 [257 269 260]]


In [ ]:
#Ensure dimensions match for multiplication
if arr2D_3.shape[1] == arr2D_4.shape[0]:
    result_dot = np.dot(arr2D_3, arr2D_4)
    print("Dot Product Result:")
    print(result_dot)

Dot Product Result:
[[ 53  59  50]
 [155 164 155]
 [257 269 260]]
